[[floor]]
level = 3
is_entry = false
is_exit = false
[[floor]]
level = 2
is_entry = false
is_exit = false
[[floor]]
level = 1
is_entry = false
is_exit = false
[[floor]]
level = 0
is_entry = true
is_exit = true
